import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        muted: "var(--muted)",
        accent: "var(--accent)",
        "on-tertiary-container": "#98805d",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#45464d",
        "on-secondary-container": "#54647a",
        "on-secondary": "#ffffff",
        "sys-background": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#bec6e0",
        "inverse-primary": "#bec6e0",
        "surface-dim": "#d8dadc",
        "on-error-container": "#93000a",
        "surface-variant": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed": "#fcdeb5",
        "surface-container": "#eceef0",
        "on-tertiary-fixed": "#271901",
        "error-container": "#ffdad6",
        "secondary-container": "#d0e1fb",
        "primary-container": "#131b2e",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-surface": "#2d3133",
        "primary-fixed": "#dae2fd",
        "on-primary-container": "#7c839b",
        "surface-tint": "#565e74",
        "secondary": "#505f76",
        "on-primary-fixed-variant": "#3f465c",
        "surface-bright": "#f7f9fb",
        "surface": "#f7f9fb",
        "outline-variant": "#c6c6cd",
        "outline": "#76777d",
        "tertiary-container": "#271901",
        "on-primary": "#ffffff",
        "primary": "#000000",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed": "#0b1c30",
        "on-surface": "#191c1e",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#574425",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "tertiary-fixed-dim": "#dec29a",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary": "#000000"
      },
      spacing: {
        "margin-mobile": "16px",
        "xl": "64px",
        "margin-desktop": "48px",
        "md": "24px",
        "lg": "40px",
        "xs": "8px",
        "gutter": "24px",
        "sm": "16px",
        "base": "4px"
      },
      fontFamily: {
        display: ["var(--font-syne)", "system-ui", "sans-serif"],
        sans: ["Inter", "var(--font-dm)", "system-ui", "sans-serif"],
        zentry: ["zentry", "sans-serif"],
        general: ["general", "sans-serif"],
        "circular-web": ["circular-web", "sans-serif"],
        "robert-regular": ["robert-regular", "sans-serif"],
        "robert-medium": ["robert-medium", "sans-serif"],
        serif: ["Fraunces", "Playfair Display", "serif"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-display": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      },
      backgroundImage: {
        "grid-fine":
          "linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)",
      },
      backgroundSize: {
        grid: "64px 64px",
      },
      keyframes: {
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "0.5" },
          "50%": { opacity: "1" },
        },
      },
      animation: {
        shimmer: "shimmer 2s infinite",
        "pulse-soft": "pulse-soft 4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
} satisfies Config;
